version: '3'

services:
  main-service:
    build: ./main-service
    container_name: kastro-main-service
    ports:
      - "5001:80"
    networks:
      - kastro-network
    restart: always

  product-service:
    build: ./product-service
    container_name: kastro-product-service
    ports:
      - "5002:80"
    networks:
      - kastro-network
    restart: always

  cart-service:
    build: ./cart-service
    container_name: kastro-cart-service
    ports:
      - "5003:80"
    networks:
      - kastro-network
    restart: always

  user-service:
    build: ./user-service
    container_name: kastro-user-service
    ports:
      - "5004:80"
    networks:
      - kastro-network
    restart: always

  order-service:
    build: ./order-service
    container_name: kastro-order-service
    ports:
      - "5005:80"
    networks:
      - kastro-network
    restart: always

  nginx:
    image: nginx:latest
    container_name: kastro-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - main-service
      - product-service
      - cart-service
      - user-service
      - order-service
    networks:
      - kastro-network
    restart: always

networks:
  kastro-network:
    driver: overlay
